version: "3.8"

services:
  micro-frontend-deploy:
    image: ghcr.io/yeolmu96/mfe-deploy-test:latest
    container_name: micro-frontend-deploy
    ports:
      - "8080:80"
    restart: always
    networks:
      - micro-front-app

networks:
  micro-front-app:
    external: true
